name: brew test-bot

concurrency:
  group: test-bot-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
    - main
  pull_request:


jobs:
  test-bot:
    strategy:
      matrix:
        os: [ ubuntu-22.04, macos-13, macos-15 ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 90
    permissions:
      actions: read
      checks: read
      contents: read
      pull-requests: read
    steps:
    - name: Set up Homebrew
      id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Cache Homebrew Bundler RubyGems
      uses: actions/cache@v4
      with:
        path: ${{ steps.set-up-homebrew.outputs.gems-path }}
        key: ${{ matrix.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
        restore-keys: ${{ matrix.os }}-rubygems-

    - name: Cache Homebrew downloads
      uses: actions/cache@v4
      with:
        path: |
          ~/Library/Caches/Homebrew
          ~/.cache/Homebrew
        key: ${{ runner.os }}-brew-cache-${{ hashFiles('**/Formula/*.rb', '**/Casks/*.rb') }}
        restore-keys: |
          ${{ runner.os }}-brew-cache-

    - run: brew test-bot --only-cleanup-before --only-setup

    - run: brew test-bot --only-tap-syntax
    - run: brew test-bot --only-formulae
      if: github.event_name == 'pull_request'

    - name: Upload bottles as artifact
      if: always() && github.event_name == 'pull_request'
      uses: actions/upload-artifact@v4
      with:
        name: bottles_${{ matrix.os }}
        path: '*.bottle.*'
